; Persistence Of Vision raytracer version 3.7 example file.
; sudo apt-get install ffmpeg
; ffmpeg -start_number 01 -i video%03d.png -vcodec mpeg4 video_ex1.mp4

Antialias=On
Display=OFF

Antialias_Threshold=0.1
Antialias_Depth=2
Input_File_Name=video.pov

Initial_Frame=1
Final_Frame=253
Initial_Clock=1
Final_Clock=253

Cyclic_Animation=on
Pause_when_Done=off
